<?php

/**
 * @file
 *   Ian's dev space
 */

/**
 * Implements hook_menu()
 */
function cirro_ian_menu() {

	// Init
	$items = array();

	$items['admin/ian'] = array(
		'title' => 'Ian dev',
		'page callback' => 'cirro_ian_admin_page',
		'access arguments' => array('claro super'),
		'type' => MENU_CALLBACK,
	);

	return $items;

}

/**
 * Build Will admin page
 */
function cirro_ian_admin_page() {

	// Init
	$html = 'HELLO Mr. STARZ';



	return $html;

}